- name: Install cron-job (ansible-pull)
  cron:
    user: ansible
    name: "Ansible provisionning"
    minute: "*/10"
    job: "/usb/bin/ansible-pull -o -U https://git.mywari.com/systamdin/teams/automation.git"
